/play_motion2:
  ros__parameters:
    controllers: [head_controller, torso_controller]

    # params for first position approach
    approach_velocity: 0.5        # default 0.5
    approach_min_duration: 0.0    # default 0.0

    motions:
      home:
        joints: [torso_lift_joint]
        positions: [0.15]
        times_from_start: [3.0]
        meta:
          name: Home
          usage: demo
          description: 'Homing'

      head_tour:
        joints: [head_1_joint, head_2_joint]
        positions: [0.0, 0.0,
                    0.7, 0.0,
                    0.7, 0.3,
                    0.7, -0.3,
                    0.7, 0.3,
                    -0.7, 0.3,
                    -0.7, -0.3,
                    0.0, 0.0]
        times_from_start: [0.1, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0]
        meta:
          name: Head Tour
          usage: demo
          description: 'Moves head to left, right, up and down'

      turn_head:
        joints: [head_1_joint, head_2_joint]
        positions: [0.0, 0.0,
                    1.0, 0.0,
                    0.0, 0.0,
                    -1.0, 0.0,
                    0.0, 0.0]
        times_from_start: [0.1, 4.0, 8.0, 12.0, 16.0]
        meta:
          name: Turn Head
          usage: tiago_finder
          description: 'Used to move tiago head to right and left side'